### PR TITLE
fix: Test fail after PR#40

### PR DESCRIPTION
**Pull request by 0xmuralik**
closes: #8

### CODE REVIEW

**Comment by 0xmuralik** [comment]
@nikugogoi @roysc  I made a few changes on laconic-sdk and laconicd (https://github.com/cerc-io/laconicd/pull/70) 
Now I'm stuck with a different error 
`signature verification failed; please verify account number (0) and chain-id (ethermint_9000-1): feePayer pubkey EthPubKeySecp256k1{02E848C9FABEED18CF49F8315ED6B4D162487B2DAEA701414EBF8BD33CF943A531} is different from transaction pubkey EthPubKeySecp256k1{0358D2444AF562B806BDF14586DF061DD969E043C93B0A780B4E4834FF313A2E86}: invalid pubkey [cerc-io/laconicd/app/ante/eip712.go:251]: unauthorized`

To recreate: checkout to murali/fix-tests on laconic-sdk and murali/record-attributes on laconicd

**Comment by dboreham** [comment]
> @nikugogoi @roysc I made a few changes on laconic-sdk and laconicd ([cerc-io/laconicd#70](https://github.com/cerc-io/laconicd/pull/70)) Now I'm stuck with a different error `signature verification failed; please verify account number (0) and chain-id (ethermint_9000-1): feePayer pubkey EthPubKeySecp256k1{02E848C9FABEED18CF49F8315ED6B4D162487B2DAEA701414EBF8BD33CF943A531} is different from transaction pubkey EthPubKeySecp256k1{0358D2444AF562B806BDF14586DF061DD969E043C93B0A780B4E4834FF313A2E86}: invalid pubkey [cerc-io/laconicd/app/ante/eip712.go:251]: unauthorized`
> 
> To recreate: checkout to murali/fix-tests on laconic-sdk and murali/record-attributes on laconicd

Hi, just noticed the message above references chain id ethermint_9000-1 -- in my scripts I changed it to laconic_9000-1.

**Comment by 0xmuralik** [comment]
> Hi, just noticed the message above references chain id ethermint_9000-1 -- in my scripts I changed it to laconic_9000-1.
As long as the chai-ID is same in both the repos, it works. Both laconicd and laconic-sdk in my PRs use ethermint chainID.
Now, only SetRecord Messages return this error. All other messages work as expected.

**Comment by AFDudley** [comment]
Can we please set the chain ID to laconic instead of ethermint? Thanks!

**Comment by dboreham** [comment]
> > Hi, just noticed the message above references chain id ethermint_9000-1 -- in my scripts I changed it to laconic_9000-1.
> 
> As long as the chai-ID is same in both the repos, it works. Both laconicd and laconic-sdk in my PRs use ethermint chainID. Now, only SetRecord Messages return this error. All other messages work as expected.

That's the wrong chain id. It should be changed in laconicd, and left as-is in laconic-sdk. See : https://github.com/cerc-io/laconicd/pull/71/files#r1058056971

**Comment by dboreham** [comment]
This seems like quite a large number of files changed in order to resolve a test regression. Could you give a bit of background on what's going on in this PR? (or does this PR incorporate some other body of work not directly related to the test fix perhaps)?

**Comment by 0xmuralik** [comment]
> Can we please set the chain ID to laconic instead of ethermint? Thanks!

Fixed that in a different open PR https://github.com/cerc-io/laconicd/pull/69

**Comment by AFDudley** [comment]
Thank you.

**Comment by 0xmuralik** [comment]
> This seems like quite a large number of files changed in order to resolve a test regression. Could you give a bit of background on what's going on in this PR? (or does this PR incorporate some other body of work not directly related to the test fix perhaps)?

Most of the changed files are due to renaming of nameservice module to "registry". You can go through the proto/vulcanize which are same as in laconicd and ignore all the src/proto files which are proto generated.
Now the main changes are refferred to the change of attributes type from string to Any. https://github.com/cerc-io/laconic-sdk/blob/e295b8de3682da9d21b2b8d6c88cb8ca24078d21/proto/vulcanize/registry/v1beta1/registry.proto#L68

**Comment by 0xmuralik** [comment]
Update:
Problem 1:
After hardcodeing record attributes in https://github.com/cerc-io/laconicd/pull/70 I found out that the issue was with EIP712 signature verification.
While unpacking the messages to generate typed data, the attributes field in record, which is of type Any, is also being unpacked to the typ of attributes Ex: Website Registration Record Attributes
But the on the client side the message with attributes as type Any is signed. And thus the difference in signBytes on laconicd and laconic-sdk.

Problem 2:
The tests on laconic-sdk rely on versioning of records but the attribute types defined on  laconicd do not have a version field. So when the record is signed on laconic-sdk and the signature is added to the payload, the signedbytes are of the record containing a version field. When we try to verify the owner of the record from signature inside the keeper, the signBytes generated there are of the record that do not have a version field and the verification of record owner fails.

**Comment by 0xmuralik** [comment]
Fixed Problem 1

**Comment by 0xmuralik** [comment]
checkout to murali/record-attributes on laconicd before running tests
except for one util test which was failing even before PR #40 everything else passes

**Comment by 0xmuralik** [comment]
All tests pass successfully and merging this now.

**Pull request merged**
